#defaults:
#  - settings_base

settings_name: settings_three
num_training_points: 5000
num_batches: 10
num_data_point_per_batch: 1000
max_independent_spikes: 3
max_correlated_spikes: 3
max_independent_drifts: 3
max_correlated_drifts: 3
num_sensors: 6
max_spike_length: 10
drift_duration: [10, 15]
drift_slope: [-0.05, 0.05]
spike_size: 2
delayed_sensors: []
sensor_background_types:
- sine_wave
- sine_wave
- sine_wave
- sine_wave
- sine_wave
- sine_wave
correlated_groups:
  group_0:
    sensor_ids:
    - 0
    - 1
    - 2
  group_1:
    sensor_ids:
    - 3
    - 4
  group_2:
    sensor_ids:
    - 0
    - 5
