#defaults:
#  - settings_base

settings_name: settings_2
num_batches: 10
num_data_point_per_batch: 1000
max_independent_spikes: 5
max_correlated_spikes: 5
max_independent_drifts: 5
max_correlated_drifts: 5
num_sensors: 6
max_spike_length: 10
drift_duration: [10, 15]
drift_slope: [-0.05, 0.05]
spike_size: 2
sensor_background_types:
- sine_wave
- ar_1_process
- poisson_moving_average
- sine_wave
- random_walk
- sine_wave
correlated_groups:
  group_0:
    sensor_ids:
    - 0
    - 1
  group_1:
    sensor_ids:
    - 2
    - 3
    - 4
