#defaults:
#  - settings_base

settings_name: settings_1
num_batches: 10
num_data_point_per_batch: 1000
max_independent_spikes: 5
max_correlated_spikes: 5
max_independent_drifts: 5
max_correlated_drifts: 5
num_sensors: 6
max_spike_length: 5
drift_duration: [15, 20]
drift_slope: [-0.05, 0.05]
spike_size: 1
sensor_background_types:
- sine_wave
- poisson_moving_average
- random_walk
- sine_wave
- poisson_moving_average
- ar_1_process
correlated_groups:
  group_0:
    sensor_ids:
    - 0
    - 1
  group_1:
    sensor_ids:
    - 2
    - 3
    - 4
  group_2:
    sensor_ids:
      - 2
      - 5